#!/usr/bin/env bash

set -euo pipefail

javac Hello.java
time java -verbose Hello

echo -----------------------------------------------------------------------

jaotc --output hello.so Hello.class
time java \
  -XX:+UnlockExperimentalVMOptions \
  -XX:+PrintAOT \
  -XX:AOTLibrary=./hello.so \
  -verbose \
  Hello
